In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

# Load your data
df = pd.read_csv("c2c.csv")
df=df[['socialNbFollows', 'productsListed', 'productsSold', 'productsPassRate', 'productsWished', 'productsBought', 'civilityGenderId', 'hasAnyApp', 'daysSinceLastLogin', 'seniority']]
from sklearn.preprocessing import MinMaxScaler,OrdinalEncoder

# Min-Max Scaling
scaler = MinMaxScaler()
X = pd.DataFrame(scaler.fit_transform(df),columns=df.columns)
print(X.columns)
import pickle
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

# Assume that your data is stored in a variable called "X_new"

# Create the pipeline
pipeline = Pipeline([
    ("scaler", MinMaxScaler()),
    ("pca", PCA(n_components=4))
])

# Fit the pipeline on the data
pipeline.fit(X)

# Save the pipeline to a file
with open("pca_pipeline.pkl", "wb") as file:
    pickle.dump(pipeline, file)

# Create the clustering model
model = KMeans(n_clusters=3)

# fit the model
model.fit(pipeline.transform(X))

# Save the model to a file
with open("clustering_model_2.pkl", "wb") as file:
    pickle.dump(model, file)

Index(['socialNbFollows', 'productsListed', 'productsSold', 'productsPassRate',
       'productsWished', 'productsBought', 'civilityGenderId', 'hasAnyApp',
       'daysSinceLastLogin', 'seniority'],
      dtype='object')

In [8]:
pd.DataFrame(X_new,columns=['socialNbFollows', 'productsListed', 'productsSold', 'productsPassRate', 'productsWished', 'productsBought', 'civilityGenderId', 'hasAnyApp', 'daysSinceLastLogin', 'seniority'])

,socialNbFollows,productsListed,productsSold,productsPassRate,productsWished,productsBought,civilityGenderId,hasAnyApp,daysSinceLastLogin,seniority
0,0.000727,0.106557,1.000000,0.74,0.039469,0.002469,0.0,1.0,0.0,0.974504
1,0.000581,0.077869,0.977011,0.99,0.000000,0.000000,0.5,1.0,0.0,0.997167
2,0.000944,0.135246,0.936782,0.94,0.003795,0.007407,0.5,1.0,0.0,0.994334
3,0.000727,0.500000,0.873563,0.92,0.002657,0.000000,0.5,1.0,0.0,0.980170
4,0.000581,0.102459,0.718391,1.00,0.000000,0.000000,0.5,0.0,0.0,0.005666
...,...,...,...,...,...,...,...,...,...,...
98908,0.000581,0.000000,0.000000,0.00,0.000000,0.000000,0.0,0.0,1.0,0.997167
98909,0.000581,0.000000,0.000000,0.00,0.000000,0.000000,0.0,1.0,1.0,0.997167
98910,0.000581,0.000000,0.000000,0.00,0.000000,0.000000,0.0,1.0,0.5,0.997167
98911,0.000581,0.000000,0.000000,0.00,0.000000,0.000000,0.5,0.0,0.0,0.997167
98912,0.000581,0.000000,0.000000,0.00,0.000000,0.000000,0.0,1.0,0.5,0.997167

In [14]:
new=pd.DataFrame(model.predict(pipeline.transform(X_new)))

In [18]:
data=pd.DataFrame(X_new,columns=['socialNbFollows', 'productsListed', 'productsSold', 'productsPassRate', 'productsWished', 'productsBought', 'civilityGenderId', 'hasAnyApp', 'daysSinceLastLogin', 'seniority'])

In [19]:
data["clus"]=new

In [22]:
data[data["clus"]==0].describe().T

,count,mean,std,min,25%,50%,75%,max
socialNbFollows,28654.0,0.000587,0.000300,0.0,0.000581,0.000581,0.000581,0.036327
productsListed,28654.0,0.000215,0.007097,0.0,0.000000,0.000000,0.000000,0.827869
productsSold,28654.0,0.000298,0.007942,0.0,0.000000,0.000000,0.000000,0.718391
productsPassRate,28654.0,0.003594,0.057452,0.0,0.000000,0.000000,0.000000,1.000000
productsWished,28654.0,0.000396,0.008997,0.0,0.000000,0.000000,0.000000,0.727135
productsBought,28654.0,0.000281,0.006495,0.0,0.000000,0.000000,0.000000,1.000000
civilityGenderId,28654.0,0.396786,0.206641,0.0,0.500000,0.500000,0.500000,1.000000
hasAnyApp,28654.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
daysSinceLastLogin,28654.0,0.838906,0.325987,0.0,1.000000,1.000000,1.000000,1.000000
seniority,28654.0,0.010479,0.005942,0.0,0.005666,0.011331,0.014164,0.019830
clus,28654.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000

In [23]:
data[data["clus"]==1].describe().T

,count,mean,std,min,25%,50%,75%,max
socialNbFollows,26174.0,0.000684,0.007455,0.0,0.000581,0.000581,0.000581,1.000000
productsListed,26174.0,0.000926,0.012386,0.0,0.000000,0.000000,0.000000,0.889344
productsSold,26174.0,0.001931,0.021236,0.0,0.000000,0.000000,0.000000,1.000000
productsPassRate,26174.0,0.021196,0.135600,0.0,0.000000,0.000000,0.000000,1.000000
productsWished,26174.0,0.001351,0.015308,0.0,0.000000,0.000000,0.000000,1.000000
productsBought,26174.0,0.000854,0.006949,0.0,0.000000,0.000000,0.000000,0.429630
civilityGenderId,26174.0,0.356957,0.232962,0.0,0.000000,0.500000,0.500000,1.000000
hasAnyApp,26174.0,1.000000,0.000000,1.0,1.000000,1.000000,1.000000,1.000000
daysSinceLastLogin,26174.0,0.671850,0.414764,0.0,0.500000,1.000000,1.000000,1.000000
seniority,26174.0,0.595920,0.477660,0.0,0.014164,0.974504,0.988669,1.000000
clus,26174.0,1.000000,0.000000,1.0,1.000000,1.000000,1.000000,1.000000

In [24]:
data[data["clus"]==2].describe().T

,count,mean,std,min,25%,50%,75%,max
socialNbFollows,44085.0,0.000585,0.000109,0.000000,0.000581,0.000581,0.000581,0.013949
productsListed,44085.0,0.000169,0.005860,0.000000,0.000000,0.000000,0.000000,1.000000
productsSold,44085.0,0.000228,0.005028,0.000000,0.000000,0.000000,0.000000,0.402299
productsPassRate,44085.0,0.003305,0.054878,0.000000,0.000000,0.000000,0.000000,1.000000
productsWished,44085.0,0.000271,0.003590,0.000000,0.000000,0.000000,0.000000,0.287287
productsBought,44085.0,0.000263,0.004263,0.000000,0.000000,0.000000,0.000000,0.688889
civilityGenderId,44085.0,0.398469,0.205851,0.000000,0.500000,0.500000,0.500000,1.000000
hasAnyApp,44085.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
daysSinceLastLogin,44085.0,0.840093,0.325614,0.000000,1.000000,1.000000,1.000000,1.000000
seniority,44085.0,0.985416,0.008768,0.971671,0.977337,0.985836,0.991501,1.000000
clus,44085.0,2.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000